---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangshengbin.
--- DateTime: 2021/8/30 下午2:56
---

local method = ngx.var.request_method
local uri = ngx.var.request_uri
--ngx.say("uri = ",uri)
if "POST" == method and "/server/api/product/apply" == uri then
    ngx.req.read_body()
    local userdata = ngx.req.get_body_data()
    local json = require("cjson")
    local args = json.decode(userdata)
    local ip = ngx.var.remote_addr

    local mysql = require "resty.mysql"
    local db, err = mysql:new()

    if not db then
        --ngx.say("failed to instantiate mysql: ", err)
        return
    end
    db:set_timeout(1000)

    -- or connect to a unix domain socket file listened
    -- by a mysql server:
    --     local ok, err, errcode, sqlstate =
    --           db:connect{
    --              path = "/path/to/mysql.sock",
    --              database = "ngx_test",
    --              user = "ngx_test",
    --              password = "ngx_test" }

    local ok, err, errcode, sqlstate = db:connect {
        host = "172.18.9.71",
        port = 3306,
        database = "test",
        user = "bfd_ibg_mf",
        password = "bfd_ibg_mf@168",
        charset = "utf8",
        max_packet_size = 1024 * 1024,
    }

    if not ok then
        --ngx.say("failed to connect: ", err, ": ", errcode, " ", sqlstate)
        return
    end
    --ngx.say("connected to mysql.")
    local insertSql = string.format("INSERT INTO `nginx_tryout_info` (`ip`,`mobile`,`userName`) VALUES(\'%s\',\'%s\',\'%s\')",ip,args.mobile,args.userName)
    local res, err, errcode, sqlstate = db:query(insertSql)
    if not res then
        --ngx.say("bad result: ", err, ": ", errcode, ": ", sqlstate, ".")
        db:close()
        return
    end
    --ngx.say(res.affected_rows, " rows inserted into table cats ", "(last insert id: ", res.insert_id, ")")
    ok, err = db:close()
    if not ok then
        --ngx.say("failed to close: ", err)
        return
    end
end
ngx.exec("@common_service")